name: Successful action
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    name: List
    runs-on: ubuntu-latest
    steps:
      - run: ls
        
          
          
